### PR TITLE
Combine `tempfile` and `tempdir` APIs

### PR DESCRIPTION
**Pull request by KodrAus**
**NOTE:** Looks like my attempt not to clobber git history while working on this has added everyone who ever contributed to `tempdir` to this PR (thanks GitHub). If you don't want notifications of my random notes please feel free to unsubscribe :) Otherwise your input would be most welcome.

This is purely an exploratory exercise.

Combining the `tempfile` and `tempdir` crates into a new ✨ _super crate_ ✨ that offers the functionality of both.

My rough plan is:

- [x] Combine the two APIs
- [x] Make them consistent with one another. Not sure what this should look like yet
- [x] Docs
- [x] Quick run through the checklist
- [x] Rebase on `tempfile:master`
- [x] Figure out next steps

The main goal of this API is to produce something that could reasonably be dropped into `std::fs` with minimal modification. That's how we'll measure success.

# Open Questions

# Changes

## `tempfile`

- Remove `AsRef<File>` from `NamedTempFile`

## `tempdir`

- Add a `tempdir` function

### CODE REVIEW

**Comment by KodrAus** [comment]
cc: @Stebalien

**Comment by KodrAus** [comment]
It looks like `TempFile` was originally a thing. But it was [replaced with the `tempfile` function in `2.0`](https://github.com/Stebalien/tempfile/commit/c78a3119c03125c87b00c972e5cd9671bf912100). The rationale is that it's just a `File`, which is what most APIs will expect.

It looks like usage is pretty fairly evenly split between `NamedTempFile::new()` and `tempfile()`. I feel like we should try and favour one approach over the other rather than have too many concepts in the crate root.

The main inconsistency between `tempdir` and `tempfile` seems to be that `tempfile` is based on the `std::File` whereas `TempDir` isn't.

**Comment by KodrAus** [comment]
I think there's also a potential philosophical rift in the `tempdir` and `tempfile` APIs where `tempfile` is trying to offer a particular set of security guarantees whereas `tempdir` isn't really (as far as I can tell right now). Or maybe more concretely the issue is that it's _hard_ to guarantee a temporary directory will behave itself and go away.

I'm guessing:

- We need a special type for temporary directories because we need to be able to drop them.
- We don't really need to get a `std::Directory` from a `TempDirectory` because we can just use the `Path`
- We don't necessarily need a special type for temporary files because we can let the OS do the cleanup

So I think we need to decide, of the two approaches to creating temporary files, which one should be recommended and then try align them.

My first thought is _do we even want named temporary files?_

And should we reinstate `TempFile` for consistency?

**Comment by Stebalien** [comment]
> My first thought is do we even want named temporary files?

Yes. Usual use-case: create a temporary file, write some data to it, run a command on it.

> It looks like usage is pretty fairly evenly split between NamedTempFile::new() and tempfile(). I feel like we should try and favour one approach over the other rather than have too many concepts in the crate root.
...
> So I think we need to decide, of the two approaches to creating temporary files, which one should be recommended and then try align them.

Python does the same thing (has named and unnamed temporary files) for the same reason.

> And should we reinstate TempFile for consistency?

There's no reason to (other than to make user's lives worse). Unlike `TempDir`, files returned by `tempfile()` are cleaned up by the OS itself.

> We need a special type for temporary directories because we need to be able to drop them.

Yes.

> We don't really need to get a std::Directory from a TempDirectory because we can just use the Path

Having a `Directory` type would allow us to provide some security guarantees.

> We don't necessarily need a special type for temporary files because we can let the OS do the cleanup

For unnamed, yes. If you want the temporary file linked into the FS, you need some drop glue.

**Comment by Stebalien** [comment]
Note: we could just drop `NamedTempFile` and tell users to use a temporary directory but that's not quite as user friendly. Currently, `NamedTempFile` implements `Read`,  `Write`, and `Seek` so it can be passed around as an owned file-like object. If users just use a temporary directory, they need to ensure that the temporary directory isn't deleted while the file is in-use (although we could use some kind of reference-counting wrapper...).

**Comment by alexcrichton** [comment]
Unfortunately I don't think I've got enough time to help out with the design here, but I trust what y'all come up with!

**Comment by KodrAus** [comment]
Thanks for clarifying @Stebalien!

I'm feeling like with `NamedTempFile` and `TempDir` it is worth having a `TempFile` type because it's easier to discover the kinds of temporary objects the crate offers. Especially since `NamedTempFile` comes with a lot of warnings about security it looks like there should be a recommended alternative, but that alternative isn't really obvious given how the rest of the crate is organised.

That's not a _really_ strong motivation though, so I think if we can mitigate the discoverability (maybe by recommending a `tempdir` and `tempfile` function over `::new()`) then I'd be happy to get rid of `TempFile` and reduce some code.

As for the `Directory` abstraction, from what you've said it seems like it would be worthwhile, but implementation-wise is a bit beyond me and my meager understanding of file systems. We could add a safe directory abstraction later as a non-breaking change, possibly.

**Comment by KodrAus** [comment]
I think these file types make more sense with `Deref` and the guideline about not adding inherent methods to smart pointers doesn't apply so much because they only hold `File`s, so there isn't ambiguity about whether methods are on `NamedTempFile` or `File`. As a smart pointer it's more like `String` than like `Box<T>`.

I do still like the idea of having `as_file`, `as_mut_file` and `into_file` methods too. So the trait implementations that `tempfile` had originally basically all make sense:

- `AsRef`
- `AsMut`
- `Deref`
- `DerefMut`

Based on the traits implemented for `String` and `str`.

**Comment by Stebalien** [comment]
>  it is worth having a TempFile type because it's easier to discover the kinds of temporary objects the crate offers.

I don't see "better documentation" as a good argument for introducing a new type. I would like some consistency/discoverability but not at the expense of usability.

> maybe by recommending a `tempdir` and `tempfile` function over `::new()`

That's a tempting solution but a bit inconsistent with the rest of the standard library. If this does ever make it into the standard library, we could go the other way and add functions to `File` (`File::temp()`, `File::temp_in(directory)`). However, that's a rather invasive solution....

For now, I think we should try better crate documentation.

**Comment by KodrAus** [comment]
I think it's less discoverability through better docs and more discoverability through consistency, whether that's looking at docs or IDE completion or source or whatever. Having a `TempFile` is more consistent, and I think that's a valid reason for it to exist.

But I'll park the `TempFile` type and see where docs leads us. I haven't really touched docs yet.

**Comment by KodrAus** [comment]
Looking at the `std::fs` module, I'm coming around to the idea of having `create_tempfile` and `create_tempdir` functions in the crate root (sans the recommendation to avoid using `::new()`). So maybe the crate layout would be something like:

```rust
struct TempDir: Drop + AsRef<Path>;
struct TempDirOptions; // TempDirBuilder? Could possibly become `fn temp` on `std::fs::DirBuilder`?

struct NamedTempFile: Drop + Read + Write + Seek + AsRef<Path> + Deref<Target = File> + DerefMut<Target = File>; // And platform specific handle traits
struct NamedTempFileOptions; // NamedTempFileBuilder?

fn create_tempfile() -> Result<File>;
fn create_tempfile_in<P: Path>(path: P) -> Result<File>;

fn create_tempdir() -> Result<TempDir>;
fn create_tempdir_in<P: Path>(path: P) -> Result<TempDir>;
```

I do think we should be careful of an explosion of functions in `std::fs` though. There seems to be a few conflicting naming conventions there too.

What do you think @Stebalien?

**Comment by Stebalien** [comment]
I'd avoid the `create_` prefix: `tempdir`, `tempfile`, and `named_tempfile` (although I wonder if we really want to provide `in` variants for these shortcuts.

> I do think we should be careful of an explosion of functions in std::fs though.

I agree. Duplicate functions are usually avoided... I'd kind of like to propose adding a `temporary()` constructor to `File` and see how the community likes it.

Also, yes, I'd go with `Builder` (`Options` is consistent with `OpenOptions` but `NewOptions` is obviously not an option).

**Comment by KodrAus** [comment]
Ok, I think this is starting to look good. And we've made very little changes to either crate.

What do you think about a `TempFileBuilder` with `create` and `create_in` methods on it? Then we can remove the `tempfile_in` method and just have `tempdir` and `tempfile`.

I'm not 100% sold on a `TempFileBuilder` yet though, honestly.

**Comment by KodrAus** [comment]
> I'd kind of like to propose adding a temporary() constructor to File and see how the community likes it.

I like this idea, it seems reasonable to me.

**Comment by KodrAus** [comment]
We might also want to tweak the `close` methods and `PersistError` based on the consensus in the [checked teardown guideline](https://github.com/rust-lang-nursery/api-guidelines/issues/61).

**Comment by Stebalien** [comment]
I'm not really seeing any consensus yet...

**Comment by KodrAus** [comment]
There isn't any to see :) I thought I'd leave a self-reminder though for when we do reach it.

**Comment by KodrAus** [comment]
What do you think if the current API we've got in this PR now @Stebalien? I'm pretty happy with it, but think it's worth getting the items right before I go flesh out the rest of the docs.

**Comment by alexcrichton** [comment]
Looking over this API it looks pretty great to me, thanks for working on this @KodrAus and @Stebalien!

I'd also sort of lean towards the name `TempFile` rather than `NamedTempFile`, but I may be missing some rationale for the "named". I'm also always a little wary of `Deref` implementations for types that aren't smart pointers, so I wonder, is this required here? Was there some functionality that'd be commonly used through `Deref`? I figured that the trait implementations were good enough to cover most of it.

**Comment by Stebalien** [comment]
> I'd also sort of lean towards the name TempFile rather than NamedTempFile, but I may be missing some rationale for the "named".

To follow the python API and make a clear separation between anonymous temporary files returned by the `tempfile()` function and named tempfiles returned by `NamedTempFile::new()`.

> I'm also always a little wary of Deref implementations for types that aren't smart pointers, so I wonder, is this required here? Was there some functionality that'd be commonly used through Deref? I figured that the trait implementations were good enough to cover most of it.

In case an API needs a `File` object. Unfortunately, there is no `FsObject: AsRawFd` for everything that lives in the filesystem. For example, my xattrs crate. We could just force the user to call an `as_file` method but that's a bit noisy.

**Comment by Stebalien** [comment]
@alexcrichton however, if we do add a `File::temporary() -> io::Result<File>` to std, we will no longer have two different types of temporary files in this crate so this will be less of an issue.

**Comment by alexcrichton** [comment]
@Stebalien oh yeah it makes total sense to me to distiguish `tempfile()`, but it's returning a `File`, right? (freeing up the name `TempFile`?)

**Comment by alexcrichton** [comment]
Also yeah accessing a `File` makes sense, but I'd imagine that to go through an `as_file` and/or `as_file_mut` accessor rather than deref (as it doesn't seem like it'd be that common to call)

**Comment by Stebalien** [comment]
> @Stebalien oh yeah it makes total sense to me to distiguish tempfile(), but it's returning a File, right? (freeing up the name TempFile?)

Yes but having a `tempfile()` function and a `TempFile` type in the same crate that do two different things is rather confusing.

> Also yeah accessing a File makes sense, but I'd imagine that to go through an as_file and/or as_file_mut accessor rather than deref (as it doesn't seem like it'd be that common to call)

I'd have to do a survey of how often people write public functions that accept `&File` and `&mut File`.

**Comment by alexcrichton** [comment]
Yeah it's true that having `tempfile()` returning `TempFile` would be a bit odd. Probably not worth it because of that!

**Comment by KodrAus** [comment]
For `Deref`, I talked myself out of it on `NamedTempFile`, then went and talked myself back in to it, using `String`/`Box` as justification. It's not a smart pointer in the sense that it _points_ to anything though, so I could easily be talked back out of it again.

I should update the names of the `file` and `file_mut` methods to match the `as_*` convention.

For generic bounds on functions you'd pass a `NamedTempFile` into, I'm assuming `Read`, `Write` and `AsRef<Path>` would be the most common. I haven't personally written APIs that expect `File`s to be passed around rather than one of those traits, but I suppose you'd run in to that at library boundaries.

**Comment by alexcrichton** [comment]
👍 

Looks great to me!

Would the next steps here be a PR to the upstream `tempfile` crate?

**Comment by KodrAus** [comment]
Sounds good! I'll go PR these changes on `tempfile` proper without worrying about keeping the history of `tempdir` and we can pick it up from there :+1:

**Pull request closed without merging**
